const ProfileData = [
  {
    id: "1",
    education1: "Uttarakhand Technical University",
    education2: "Government Polytechnic Shyampur",
    degree1: "Bachelor of Technology",
    degree2: "Diploma of Education",
    degreein1: "Computer Science",
    degreein2: "Electrical Engineering",
    started1: "Oct 2021",
    started2: "Aug 2018",
    Endedin1: "Aug 2024",
    Endedin2: "Oct 2021",
    Experience1: "Intern",
    Experience2: "Full Stack Developer",
    CompanyName1: "THDC India Limited Official",
    CompanyName2: "Google",
    Role1: "Internship",
    Role2: "Full Time",
    notification1: "event #1 for the alumni's",
    notification2: "event #2 for the alumni's",
    profileImg: "https://source.unsplash.com/random/?kitchen",
    backgroundImg: "https://source.unsplash.com/random/?food",
    comment1: "loved this post",
    comment2: "loved this post",
    name: "Priyanshu Bhatt",
    bio: "Alumni batch 2024",
    district: "Dehradun",
    state: "Uttarakhand",
    country: "India",
    link: "#",
    phone: "1234567890",
    email: "nobody123@xyz.com",
    skill1: "FrontEnd Developer",
    skill2: "Backend Developer",
    achivement1: "Winner in Hackathon",
    achivement2: "Participated in TechSummit",
    achivement3: "Hosted the Geo-Summit",
    para1: "Won the hackathon of 2k23",
    para2: "Participated in the Techsummit held in the college 2k24",
    para3: "Hosted the geo Summit 2K25 on the topic of sustainable development",
    utu: "/utu.png",
    sampleImg1: "/sample.svg",
    sampleImg2: "/sample2.png",
    sampleEImg: "/institute.avif",
    achivDateStart1: "15 May 2023",
    achivDateStart2: "14 Sept 2024",
    achivDateEnd1: "23 May 2023",
    achivDateEnd2: "14 Sept 2024",
  },
];

export default ProfileData;
