const ProfileData = [
  {
    id: "1",
    education1: "Uttarakhand Technical University",
    education2: "Government Polytechnic Shyampur",
    degree1: "Bachelor of Technology",
    degree2: "Diploma of Education",
    degreein1: "Computer Science",
    degreein2: "Electrical Engineering",
    started1: "Oct 2021",
    started2: "Aug 2018",
    Endedin1: "Aug 2024",
    Endedin2: "Oct 2021",
    Experience1: "Intern",
    Experience2: "Full Stack Developer",
    CompanyName1: "THDC India Limited Official",
    CompanyName2: "Google",
    Role1: "Internship",
    Role2: "Full Time",
    notification1: "event #1 for the alumni's",
    notification2: "event #2 for the alumni's",
    profileImg: "https://source.unsplash.com/random/?kitchen",
    backgroundImg: "https://source.unsplash.com/random/?food",
    comment1: "loved this post",
    comment2: "loved this post",
    name: "Priyanshu Bhatt",
    bio: "Alumni batch 2024",
    district: "Dehradun",
    state: "Uttarakhand",
    country: "India",
    link: "#",
    phone: "1234567890",
    email: "nobody123@xyz.com",
    skill1: "FrontEnd Developer",
    skill2: "Backend Developer",
  },
];

export default ProfileData;
